version: '3'

services:
  app_vet:
    build: vet
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:h2:mem:clinica_veterinaria;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
      SPRING_DATASOURCE_DRIVERCLASSNAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: sa
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: always

